### ISSUE TITLE
Random crashing

### ISSUE THREAD

**Issue by MathiasTopKek** [azaelgg/meteoric#12]
Hey i'm trying to run your sniper on a windows 2019 sever but i notice that the sniper closes itself randomly without any errors?

**Comment by post04** [comment]
> Hey i'm trying to run your sniper on a windows 2019 server but i notice that the sniper closes itself randomly without any errors?

We've noticed this happens when the internet connection is lost for any amount of time. We're looking into it.

**Comment by MathiasTopKek** [comment]
I haven't noticed that issue with a sniper made in rust or javascript hmm

**Comment by post04** [comment]
> I haven't noticed that issue with a sniper made in rust or javascript hmm

The language has nothing to do with it, all those snipers are using packages with years worth of edge cases tested whereas our custom-made WebSocket implementation doesn't.

**Comment by MathiasTopKek** [comment]
Well nonetheless the issue still persists i tried to make it automatically restart on crash/when it closes but without success either it just results in the sniper mass opening and closing itself.

**Comment by azaelgg** [comment]
yeah we're aware of this issue, currently if the connection drops for a split second or you connect/disconnect from a VPN, it'll happen.

**Comment by MathiasTopKek** [comment]
> yeah we're aware of this issue, currently if the connection drops for a split second or you connect/disconnect from a VPN, it'll happen.

i'm monitoring my server 24/7 it had no connections issues over the past 40 days

**Comment by MathiasTopKek** [comment]
I managed to log the error it gives when it crashes, if that gives you any hints or somehow helps on debugging? 
`panic: repeated read on failed websocket connection

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).NextReader(0xc0000f8840, 0xffffffffffffffff, 0x0, 0x0, 0x635dc0, 0xc0065e7e60)
        C:/Users/sss/go/src/github.com/gorilla/websocket/conn.go:1001 +0x34d
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc0000f8840, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x635dc0, 0xc0065e7e60)
        C:/Users/sss/go/src/github.com/gorilla/websocket/conn.go:1064 +0x36
_/C_/Users/sss/Desktop/meteoric-main/discord.(*Session).Open(0xc0000e87c0)
        C:/Users/sss/Desktop/meteoric-main/discord/gateway.go:85 +0x3d
main.main()
        C:/Users/sss/Desktop/meteoric-main/main.go:27 +0x1cc`
